eShop.web/Models/Blocks/LoginControlBlock.cs
using EPiServer;
using EPiServer.Core;
using EPiServer.DataAbstraction;
using EPiServer.DataAnnotations;
using eShop.web.ViewModels;
using System.ComponentModel.DataAnnotations;

namespace eShop.web.Models.Blocks
{
    [ContentType(
        DisplayName = "Login Control Block", 
        GUID = "3452515d-8188-4c09-b3de-00ce8e789c48", 
        Description = "The login Form data")]
    [BlockSiteImageUrl]
    public class LoginControlBlock : SiteBlockData
    {
        [Ignore]
        public LoginModel LoginModel { get; set; }

        [CultureSpecific]
        [Display(Name = "Block Name",
            GroupName = SystemTabNames.Content,
            Order = 100)]
        [Required]
        public virtual string BlockName { get; set; }

        [CultureSpecific]
        [Display(Name = "Block Description",
            GroupName = SystemTabNames.Content,
            Order = 200)]
        [Required]
        public virtual XhtmlString BlockDescription { get; set; }

        [CultureSpecific]
        [Display(Name = "User Name Label",
            GroupName = SystemTabNames.Content,
            Order = 300)]
        [Required]
        public virtual string UserNameLabel { get; set; }

        [CultureSpecific]
        [Display(Name = "User Name Placeholder",
            GroupName = SystemTabNames.Content,
            Order = 400)]
        [Required]
        public virtual string UserNamePlaceholder { get; set; }

        [CultureSpecific]
        [Display(Name = "Password Label",
            GroupName = SystemTabNames.Content,
            Order = 500)]
        [Required]
        public virtual string PasswordLabel { get; set; }

        [CultureSpecific]
        [Display(Name = "Forgot Your Password Text",
            GroupName = SystemTabNames.Content,
            Order = 700)]
        [Required]
        public virtual string ForgotYourPasswordText { get; set; }

        [CultureSpecific]
        [Display(Name = "Forgot Your Password Url",
            GroupName = SystemTabNames.Content,
            Order = 800)]
        [Required]
        public virtual Url ForgotYourPasswordUrl { get; set; }

        [CultureSpecific]
        [Display(Name = "Remember Me Text",
            GroupName = SystemTabNames.Content,
            Order = 900)]
        [Required]
        public virtual string RememberMeText { get; set; }

        [CultureSpecific]
        [Display(Name = "Sign-In Text",
            GroupName = SystemTabNames.Content,
            Order = 1000)]
        [Required]
        public virtual string SignInText { get; set; }

        [CultureSpecific]
        [Display(Name = "Sign-In Form Url",
            GroupName = SystemTabNames.Content,
            Order = 1100)]
        [Required]
        public virtual Url SignInFormUrl { get; set; }
    }
}

eShop.web/ViewModels/LoginControlBlockViewModel.cs
using eShop.web.Models.Blocks;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace eShop.web.ViewModels
{
    public class LoginControlBlockViewModel : BlockViewModel<LoginControlBlock>
    {
        public LoginControlBlockViewModel(LoginControlBlock loginControlBlock) : base(loginControlBlock)
        {
            
        }
    }
}

eShop.web/Controllers/LoginControlBlockController.cs
using EPiServer.Core;
using EPiServer.Web;
using EPiServer.Web.Mvc;
using EPiServer.Web.Routing;
using eShop.web.Business.Filters;
using eShop.web.Models.Blocks;
using eShop.web.Models.Pages;
using eShop.web.ViewModels;
using System.Web.Mvc;
using System.Web.Security;

namespace eShop.web.Controllers
{
    public class LoginControlBlockController : BaseFormBlockController<LoginControlBlock>
    {
        //[ImportModelStateFromTempDataFilter]
        public override ActionResult Index(LoginControlBlock currentBlock)
        {
            var viewModel = new LoginControlBlockViewModel(currentBlock)
            {
                CurrentPage = CurrentPage,
                CurrentPageLink = CurrentPageLink
            };

            LoadModelState(viewModel.CurrentBlockLink, out var oldModel);
            viewModel.CurrentBlock.LoginModel = (LoginModel)oldModel;

            return PartialView(viewModel);
        }

        //[ExportModelStateToTempDataFilter]
        [HttpPost]
        public ActionResult Login(LoginModel model, PageReference currentPageLink, ContentReference currentBlockLink)
        {
            var returnUrl = UrlResolver.Current.GetUrl(currentPageLink);

            if (ModelState.IsValid && Membership.ValidateUser(model.Username, model.Password))
            {
                FormsAuthentication.SetAuthCookie(model.Username, model.RememberMe);
            }
            else
            {
                ModelState.AddModelError(string.Empty, "Log-in Failed");
                SaveModelState(currentBlockLink, model);
            }


            return Redirect(returnUrl);
        }

        public ActionResult Logout()
        {
            FormsAuthentication.SignOut();
            var returnUrl = UrlResolver.Current.GetUrl(SiteDefinition.Current.StartPage);
            return Redirect(returnUrl);
        }
    }
}

eShop.web/Views/LoginControlBlock/Index.cshtml
@model  eShop.web.ViewModels.LoginControlBlockViewModel
@{
    var loginModel = Model.CurrentBlock.LoginModel ?? new LoginModel();
    bool isLoggedin = false;
    if (Request.Cookies.Get(FormsAuthentication.FormsCookieName) != null)
    {
        isLoggedin = true;
    }
}

@if (isLoggedin)
{
    <a href="/LoginControlBlock/Logout">Logout</a>
}
else
{
    using (Html.BeginForm("Login", "LoginControlBlock", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        @Html.Hidden("currentPageLink", Model.CurrentPageLink)
        @Html.Hidden("currentBlockLink", Model.CurrentBlockLink)


        <h1>
            @Model.CurrentBlock.BlockName
        </h1>

        <div>
            @Html.PropertyFor(x => x.CurrentBlock.BlockDescription)
        </div>

        <div class="text-warning">
            @Html.ValidationSummary()
        </div>

        <div>
            @Html.Label(@Model.CurrentBlock.UserNameLabel)
            <input type="text" name="Username" value="@loginModel.Username" placeholder="@Model.CurrentBlock.UserNamePlaceholder">
        </div>

        <div>
            @Html.Label(@Model.CurrentBlock.PasswordLabel)
            <input type="password" name="Password" value="@loginModel.Password">
        </div>

        <div>
            <button href="@Model.CurrentBlock.SignInFormUrl">
                @Model.CurrentBlock.SignInText
            </button>
        </div>

        <div>
            <a src="@Model.CurrentBlock.ForgotYourPasswordUrl">
                @Model.CurrentBlock.ForgotYourPasswordText
            </a>
        </div>

        <div>

            @Html.CheckBox("RememberMe", @loginModel.RememberMe)
            @Model.CurrentBlock.RememberMeText

        </div>
    }
}