eShop.web/Models/Pages/CheckoutPage.cs
using EPiServer.Core;
using EPiServer.DataAbstraction;
using EPiServer.DataAnnotations;
using EPiServer.SpecializedProperties;
using System;
using System.ComponentModel.DataAnnotations;

namespace eShop.web.Models.Pages
{
    [ContentType(DisplayName = "Checkout Page",
        GUID = "395390f1-355d-4919-b9d7-50206dd4e1f8", 
        Description = "")]
    public class CheckoutPage : SitePageData
    {
        /*
                [CultureSpecific]
                [Display(
                    Name = "Main body",
                    Description = "The main body will be shown in the main content area of the page, using the XHTML-editor you can insert for example text, images and tables.",
                    GroupName = SystemTabNames.Content,
                    Order = 1)]
                public virtual XhtmlString MainBody { get; set; }
         */
    }
}

eShop.web/Controllers/CheckoutPageController.cs
using EPiServer;
using EPiServer.Commerce.Catalog.ContentTypes;
using EPiServer.Commerce.Catalog.Linking;
using EPiServer.Commerce.Order;
using EPiServer.Core;
using EPiServer.Framework.DataAnnotations;
using EPiServer.Framework.Localization;
using EPiServer.ServiceLocation;
using EPiServer.Web;
using EPiServer.Web.Mvc;
using EPiServer.Web.Mvc.Html;
using EPiServer.Web.Routing;
using eShop.web.Business.Services;
using eShop.web.Helpers;
using eShop.web.Models.Commerce;
using eShop.web.Models.Pages;
using eShop.web.ViewModels;
using Mediachase.Commerce;
using Mediachase.Commerce.Catalog;
using Mediachase.Commerce.Catalog.Objects;
using Mediachase.Commerce.Customers;
using Mediachase.Commerce.Markets;
using Mediachase.Commerce.Orders;
using Mediachase.Commerce.Orders.Managers;
using Mediachase.Commerce.Pricing;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Web.Mvc;

namespace eShop.web.Controllers
{
    public class CheckoutPageController : BasePageController<CheckoutPage>
    {

        IOrderRepository _orderRepository;
        ReferenceConverter _referenceConverter;
        IContentLoader _contentLoader;
        IOrderGroupFactory _orderGroupFactory;
        IPriceService _priceService;
        ICurrentMarket _currentMarket;
        CookieService _cookieService;
        OrderValidationService _orderValidationService;
        IMarketService _marketService;
        IShippingPlugin _shippingPlugins;
        IShippingGateway _shippingGateways;
        UrlResolver _urlResolver;
        IRelationRepository _relationRepository;
        IOrderGroupCalculator _orderGroupCalculator;
        IPaymentProcessor _paymentProcessor;
        LocalizationService _localizationService;

        public CheckoutPageController()
        {
            _orderRepository = ServiceLocator.Current.GetInstance<IOrderRepository>();
            _referenceConverter = ServiceLocator.Current.GetInstance<ReferenceConverter>();
            _contentLoader = ServiceLocator.Current.GetInstance<IContentLoader>();
            _orderGroupFactory = ServiceLocator.Current.GetInstance<IOrderGroupFactory>();
            _currentMarket = ServiceLocator.Current.GetInstance<ICurrentMarket>();
            _cookieService = ServiceLocator.Current.GetInstance<CookieService>();
            _orderValidationService = ServiceLocator.Current.GetInstance<OrderValidationService>();
            _priceService = ServiceLocator.Current.GetInstance<IPriceService>();
            _marketService = ServiceLocator.Current.GetInstance<IMarketService>();
            _shippingPlugins = ServiceLocator.Current.GetInstance<IShippingPlugin>();
            _shippingGateways = ServiceLocator.Current.GetInstance<IShippingGateway>();
            _relationRepository = ServiceLocator.Current.GetInstance<IRelationRepository>();
            _urlResolver = ServiceLocator.Current.GetInstance<UrlResolver>();
            _orderGroupCalculator = ServiceLocator.Current.GetInstance<IOrderGroupCalculator>();
            _paymentProcessor = ServiceLocator.Current.GetInstance<IPaymentProcessor>();
            _localizationService = ServiceLocator.Current.GetInstance<LocalizationService>();
        }

        public ActionResult Index(CheckoutPage currentPage)
        {
            /* Implementation of action. You can create your own view model class that you pass to the view or
             * you can pass the page type for simpler templates */
            
            var model = new CheckoutViewModel
            {
                //CurrentPage = currentPage,
                Shipments = new List<ShipmentViewModel>(),
                //AppliedCouponCodes = new List<string>(),
                CurrentPage = currentPage,
                StartPage = _contentLoader.Get<StartPage>(ContentReference.StartPage),
                AvailableAddresses = new List<AddressModel>(),
                UseBillingAddressForShipment = true
            };

            //if (Cart != null && Cart.GetAllLineItems().Any())
            {
                var currentShippingAddressId = Cart.GetFirstShipment()?.ShippingAddress?.Id;
                var currentBillingAdressId = Cart.GetFirstForm().Payments.FirstOrDefault()?.BillingAddress?.Id;

                foreach (var shipment in Cart.GetFirstForm().Shipments)
                {
                    var shipmentModel = new ShipmentViewModel
                    {
                        ShipmentId = shipment.ShipmentId,
                        CartItems = new List<CartItemViewModel>(),
                        Address = ConvertToModel(shipment.ShippingAddress),
                        ShippingMethods = CreateShippingMethodViewModels(Cart.MarketId, Cart.Currency, shipment)
                    };

                    shipmentModel.ShippingMethodId = shipment.ShippingMethodId == Guid.Empty && shipmentModel.ShippingMethods.Any() ?
                                                 shipmentModel.ShippingMethods.First().Id
                                               : shipment.ShippingMethodId;

                    var codes = shipment.LineItems.Select(x => x.Code);
                    var entries = _contentLoader.GetItems(
                                    codes
                                        .Select(x => _referenceConverter.GetContentLink(x))
                                        .Where(r => !ContentReference.IsNullOrEmpty(r)),
                                    //_languageResolver.GetPreferredCulture()
                                    GetCurrentLanguage()
                                    ).OfType<EntryContentBase>();

                    foreach (var lineItem in shipment.LineItems)
                    {
                        var entry = entries.FirstOrDefault(x => x.Code == lineItem.Code);
                        if (entry == null)
                        {
                            //Entry was deleted, skip processing.
                            continue;
                        }

                        shipmentModel.CartItems.Add(CreateCartItemViewModel(Cart, lineItem, entry));
                    }
                    model.Shipments.Add(shipmentModel);
                }

                var customer = CustomerContext.Current.CurrentContact;
                var useBillingAddressForShipment =
                       model.Shipments.Count == 1 && currentBillingAdressId == currentShippingAddressId &&
                       (customer == null ||
                       customer.PreferredShippingAddressId.HasValue &&
                       customer.PreferredShippingAddressId == customer.PreferredBillingAddressId);

                model.BillingAddress = CreateBillingAddressModel();
                model.BillingAddress.CountryOptions = CountryManager.GetCountries().Country.Select(x => new CountryViewModel { Code = x.Code, Name = x.Name });

                model.UseBillingAddressForShipment = useBillingAddressForShipment;
                model.AvailableAddresses = AddressList();

                UpdateShippingAddresses(Cart, model);
                UpdateShippingMethods(Cart, model.Shipments);

                //_cartService.ApplyDiscounts(Cart);
                _orderRepository.Save(Cart);
            }

            return View(model);
        }

        [HttpPost]
        public ActionResult Purchase(CheckoutViewModel viewModel)
        {
            if (Cart == null || !Cart.GetAllLineItems().Any())
            {
                return Redirect(Url.ContentUrl(ContentReference.StartPage));
            }    
            
            //address
            viewModel.BillingAddress.CountryOptions = CountryManager.GetCountries().Country.Select(x => new CountryViewModel { Code = x.Code, Name = x.Name });
            viewModel.BillingAddress.CountryRegion.RegionOptions = Enumerable.Empty<string>();
            var issues = _orderValidationService.ValidateOrder(Cart);

            
            // validate email in billding address
            //..

            // use shipping same billing address
            Cart.GetFirstShipment().ShippingAddress = ConvertToAddress(viewModel.BillingAddress, Cart);

            //create payment
            foreach (var form in Cart.Forms)
            {
                form.Payments.Clear();
            }

            var method = GetPaymentMethod().FirstOrDefault(x => x.SystemKeyword == viewModel.SystemKeyword);

            var total = Cart.GetTotal(_orderGroupCalculator);
            var payment = CreatePayment(total.Amount, Cart, method.PaymentMethodId, viewModel.SystemKeyword);
            Cart.AddPayment(payment, _orderGroupFactory);
            payment.BillingAddress = ConvertToAddress(viewModel.BillingAddress, Cart);

            //process
            var paymentProcessingResults = Cart.ProcessPayments(_paymentProcessor, _orderGroupCalculator).ToList();
            if (paymentProcessingResults.Any(r => !r.IsSuccessful))
            {
                ModelState.AddModelError("", _localizationService.GetString("/Checkout/Payment/Errors/ProcessingPaymentFailure") + string.Join(", ", paymentProcessingResults.Select(p => p.Message)));
                return null;
            }

            var redirectPayment = paymentProcessingResults.FirstOrDefault(r => !string.IsNullOrEmpty(r.RedirectUrl));
            if (redirectPayment != null)
            {
                return null;
            }

            var processedPayments = Cart.GetFirstForm().Payments.Where(x => x.Status.Equals(PaymentStatus.Processed.ToString())).ToList();
            if (!processedPayments.Any())
            {
                // Return null in case there is no payment was processed.
                return null;
            }

            var totalProcessedAmount = processedPayments.Sum(x => x.Amount);
            if (totalProcessedAmount != Cart.GetTotal(_orderGroupCalculator).Amount)
            {
                throw new InvalidOperationException("Wrong amount");
            }

eShop.web/Views/CheckoutPage/Index.cshtml
@model CheckoutViewModel

<!-- Checkout Section Begin -->
<section class="checkout spad">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <h6 class="coupon__link">
                    <span class="icon_tag_alt"></span> <a href="#">Have a coupon?</a> Click
                    here to enter your code.
                </h6>
            </div>
        </div>
        <form  action="@Url.Action("Purchase", "CheckoutPage")" method="post" novalidate  class="checkout__form">
            @Html.HiddenFor(model => model.BillingAddress.Name)
            @Html.HiddenFor(model => model.UseBillingAddressForShipment)
            @Html.HiddenFor(model => model.BillingAddress.DaytimePhoneNumber)
            @Html.HiddenFor(model => model.BillingAddress.BillingDefault)
            @Html.HiddenFor(model => model.BillingAddress.ShippingDefault)
            @Html.HiddenFor(model => model.CurrentPageLink)

            <div class="row">
                <div class="col-lg-8">
                    <h5>Billing detail</h5>
                    <div class="row">
                        <div class="col-lg-6 col-md-6 col-sm-6">
                            <div class="checkout__form__input">
                                <p>First Name <span>*</span></p>
                                @*<input type="text">*@
                                @Html.TextBoxFor(model => model.BillingAddress.FirstName)
                            </div>
                        </div>
                        <div class="col-lg-6 col-md-6 col-sm-6">
                            <div class="checkout__form__input">
                                <p>Last Name <span>*</span></p>
                                @*<input type="text">*@
                                @Html.TextBoxFor(model => model.BillingAddress.LastName)
                            </div>
                        </div>
                        <div class="col-lg-12">
                            <div class="checkout__form__input">
                                <p>Country <span>*</span></p>
                                @*<input type="text">*@
                                @Html.DropDownListFor(model => model.BillingAddress.CountryCode, new SelectList(Model.BillingAddress.CountryOptions, "Code", "Name", Model.BillingAddress.CountryCode))
                            </div>
                            <div class="checkout__form__input">
                                <p>Address<span>*</span></p>
                                @*<input type="text" placeholder="Street Address">
            <input type="text" placeholder="Apartment. suite, unite ect ( optinal )">*@
                                @Html.TextBoxFor(model => model.BillingAddress.Line1, new { @class = "form-control" })
                            </div>
                            <div class="checkout__form__input">
                                <p>Town/City <span>*</span></p>
                                @Html.TextBoxFor(model => model.BillingAddress.City)
                            </div>
                            <div class="checkout__form__input">
                                <p>Country/State <span>*</span></p>
                                @*<input type="text">*@
                                @Html.EditorFor(model => model.BillingAddress.CountryRegion, Model.BillingAddress.CountryRegion)
                            </div>
                            <div class="checkout__form__input">
                                <p>Postcode/Zip <span>*</span></p>
                                @*<input type="text">*@
                                @Html.TextBoxFor(model => model.BillingAddress.PostalCode)
                            </div>
                        </div>
                        <div class="col-lg-6 col-md-6 col-sm-6">
                            <div class="checkout__form__input">
                                <p>Phone <span>*</span></p>
                                <input type="text">
                            </div>
                        </div>
                        <div class="col-lg-6 col-md-6 col-sm-6">
                            <div class="checkout__form__input">
                                <p>Email <span>*</span></p>
                                @*<input type="text">*@
                                @Html.TextBoxFor(model => model.BillingAddress.Email)
                            </div>
                        </div>
                        @*<div class="col-lg-12">
                            <div class="checkout__form__checkbox">
                                <label for="acc">
                                    Create an acount?
                                    <input type="checkbox" id="acc">
                                    <span class="checkmark"></span>
                                </label>
                                <p>
                                    Create am acount by entering the information below. If you are a returing
                                    customer login at the <br />top of the page
                                </p>
                            </div>
                            <div class="checkout__form__input">
                                <p>Account Password <span>*</span></p>
                                <input type="text">
                            </div>
                            <div class="checkout__form__checkbox">
                                <label for="note">
                                    Note about your order, e.g, special noe for delivery
                                    <input type="checkbox" id="note">
                                    <span class="checkmark"></span>
                                </label>
                            </div>
                            <div class="checkout__form__input">
                                <p>Oder notes <span>*</span></p>
                                <input type="text"
                                       placeholder="Note about your order, e.g, special noe for delivery">
                            </div>
                        </div>*@
                    </div>
                </div>
                <div class="col-lg-4">
                    @{
                        Html.RenderAction("CartSideBar", "Cart");
                    }
                </div>
            </div>
        </form>
    </div>
</section>
<!-- Checkout Section End -->

eShop.web/Views/CheckoutPage/Purchase.cshtml
@model PurchaseOrderViewModel
@section styles{
    <style>
        body {
            text-align: center;
            padding: 40px 0;
            background: #EBF0F5;
        }

        h1 {
            color: #88B04B;
            font-family: "Nunito Sans", "Helvetica Neue", sans-serif;
            font-weight: 900;
            font-size: 40px;
            margin-bottom: 10px;
        }

        p {
            color: #404F5E;
            font-family: "Nunito Sans", "Helvetica Neue", sans-serif;
            font-size: 20px;
            margin: 0;
        }

        i {
            color: #9ABC66;
            font-size: 100px;
            line-height: 200px;
            margin-left: -15px;
        }

        .card {
            background: white;
            padding: 60px;
            border-radius: 4px;
            box-shadow: 0 2px 3px #C8D0D8;
            display: inline-block;
            margin: 0 auto;
        }
    </style>
}
<div class="card">
    <div style="border-radius:200px; height:200px; width:200px; background: #F8FAF5; margin:0 auto;">
        <i class="checkmark">✓</i>
    </div>
    <h1>@Html.Translate("/checkout/success")</h1>
    <p>We received your purchase request;<br /> we'll be in touch shortly!</p>
    <p>your order number : @Model.OrderNumber</p>
</div>